### ISSUE TITLE
Elegantly handling the goroutines

### ISSUE THREAD

**Issue by kshitij10496** [peterbourgon/how-i-start-go#7]
Hey @peterbourgon 

Thanks for the excellent article. ❤️  
It taught me a lot about developing clean handlers in Go.

In general, I had a conceptual question regarding the [handling erroneous goroutines](https://github.com/peterbourgon/how-i-start-go/blob/2efe26d5503e8200b72a42e1f56512e4b40ac16f/main.go#L75) i.e. goroutines returning an error.

Suppose I have 10 different `weatherProviders` and I use concurrency to fetch the temperature from all of them using 10 goroutines. Now, if the fastest of these providers return an `error`, the `multiWeatherProvider` returns according to the current implementation. 
However, all the other 9 goroutines are still running in background, right? 
- Does this not result in a resource leak in terms of memory? 
- Should we not wait for all of them to complete and then decide upon the response?
- What should be the best practice here?

**Comment by peterbourgon** [comment]
> Does this not result in a resource leak in terms of memory?

A goroutine "leaks" if it stays running forever and we lose track of it. Often, the way that happens is by trying to send on a chan that isn't buffered, or doesn't have a matching receiver. So yes, this could be that situation, except for one detail: the [temps and errs chans](https://github.com/peterbourgon/how-i-start-go/blob/2efe26d5503e8200b72a42e1f56512e4b40ac16f/main.go#L51-L52) are declared to have a buffer equal to the number of goroutines we eventually start. So, if there's an error, we just take it and return it, while all the remaining goroutines are still running. But, even though we've lost track of them, they're free to push into that chan, because it has buffer capacity, and so they do eventually exit, and don't leak.

> Should we not wait for all of them to complete and then decide upon the response?

Maybe. It might be a better implementation to collect any errors but continue processing, and then... do what with the error? Ignore it, and calculate an average based on the successful responses? Return it anyway? It's not idiomatic to return a (somehow) correct value _and_ an error, so we'd probably not do that. I think it's ambiguous! I think in the cases of ambiguity, it's generally better to "fail fast" and report an error rather than a (partial) success. But, it's a judgment call.
